<?php require('template/header.phtml');
?>
    <script src="../js/markerclusterer.js"></script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1M6bF-9b5Kc3XFPDbI5wJNZEqrYVVH3s&callback=initMap">
    </script>
    <div class="empty-box">
    </div>
    <ul class ="postpage" id="box">
        <br>
        <br>
        <div class="campsite-slider">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block mx-auto img-fluid" src="/images/campsites/firstcamp.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block mx-auto img-fluid" src="/images/campsites/secondcamp.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block mx-auto img-fluid" src="/images/campsites/thirdcamp.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div id="map" class="mainMap"></div>
        <br>
        <?php
                    $nameArr = [];
                     if(is_array($view->campsiteDataSet)){
                         foreach ($view->campsiteLocation as $campLoc) {
                             $name = $campLoc->getCampName();
                             $lat = $campLoc->getCampLat();
                             $long = $campLoc->getCampLong();
                             $id = $campLoc->getCampID();
                             $photo = $campLoc->getMainImage();

                             $nameArr[] = $name;
                             $latArr[] = $lat;
                             $longArr[] = $long;
                             $idArr[] = $id;
                             $photoArr[] = $photo;
                         }
                     }

                     function utf8ize($nameArr) {
                        if (is_array($nameArr)) {
                            foreach ($nameArr as $k => $v) {
                                $nameArr[$k] = utf8ize($v);
                             }
                         } else if (is_string ($nameArr)) {
                            return utf8_encode($nameArr);
                         }
                            return $nameArr;
                         }


                         foreach ($view->campsiteDataSet as $campData) {
                             echo '<li class="camp-post" id= "' . $campData->getCampID() . '"
                             <article data-standout-type id="postlist">
                                <section class="content-column">
                                    <div class="<!--  -->ampsite-information">
                                        <header class="campsite-header">'.$campData->getCampName() .'</header>
                                            <p class="campsite-information"><img src="'.$campData->getMainImage().'" class="camp-image" >';
                             if(isset($_SESSION['login_user'])){
                                 echo "Campsite Address: " . $campData->getCampAddress() . '<br>'."Campsite Country: " . $campData->getCampCountry(). '<br>' . "Campsite Email: " . $campData->getCampEmail() . '<br>' . "Campsite Phone: " . $campData->getCampPhone() . '<br>';
                             }else{
                                 echo "Please signin first to see more information";
                                 echo '<br>';
                             }
                             if($campData->getCampToilet() != null || $campData->getCampPool() != null || $campData->getCampWifi() != null || $campData->getCampWaterSup() != null || $campData->getCampChildrenPlay() != null){
                                 echo 'Campsite Facilities: ' . $campData->getCampToilet() ." " . $campData->getCampPool() ." ". $campData->getCampWifi() ." ". $campData->getCampWaterSup() ." ". $campData->getCampChildrenPlay();
                                 echo '<br>';
                             }
                             echo "Campsite Open Date: ". $campData->getCampOpenDate();
                             echo '</p>
                                    </div>
                                    <div class="button-camp">
                                        <form type="post" action="../view.php">
                                            <input type="hidden" id="CampID" name="campIDhidden" value="'. $campData->getCampID() .'">
                                                <input type="submit" name="View" value="View">' . '</p>
                                        </form>
                                    <form method="post" action="../index.php">
                                        <input type="hidden" id="CampID" name="campIDhidden" value="'. $campData->getCampID() .'">';
                             if (isset($_SESSION['login_user'])) {
                                 echo '<input type="submit" name="addToFavorites" id="addToFavorites" value="Add to favorites">';
                             }
                             echo '</form>
                                </div>' . '</section>' . '</article>' . '</li>';
                         }
                         echo '</div>'; ?>

         <script type="text/javascript">
             function initMap() {
                 var jName = <?php echo json_encode(utf8ize($nameArr)); ?>;
                 var jLong =<?php echo json_encode($longArr);?>;
                 var jLat = <?php echo json_encode($latArr);?>;
                 var jPhoto = <?php echo json_encode($photoArr);?>;
                 var jId = <?php echo json_encode($idArr);?>;

                 var locations = [];
                 for(var b = 0; b < jLong.length; b++){
                     locations[b] = [jName[b], jLat[b], jLong[b], jPhoto[b], jId[b]];
                 }

                 var map = new google.maps.Map(document.getElementById('map'), {
                     zoom: 4,
                     center: new google.maps.LatLng(50.3785, 14.9706),
                     mapTypeId: google.maps.MapTypeId.ROADMAP
                 });
                 map.setOptions({ minZoom: 3, maxZoom: 15 });

                 var infowindow = new google.maps.InfoWindow();

                 for (var i = 0; i < locations.length; i++){
                     // pull the marker data into named variables
                     var name = locations[i][0];
                     var lat = locations[i][1];
                     var long = locations[i][2];
                     var photo = locations[i][3];
                     var id = locations[i][4];

                     // create a latlng object for the marker
                     latlngset = new google.maps.LatLng(lat, long);

                     // add the marker
                     var marker = new google.maps.Marker({
                         map: map,
                         title: name,
                         position: latlngset
                     });

                     var content = "<div class='infoWindow'>" +  "<p class='infoWindowTitle text-center'>" + name + "</p>" +
                         "<img class='infoWindowImg center-block' id='map-img' src='../" + photo + "' alt='no pic'>" +
                         "<p class='infoWindowInfo'><a href='../view.php?campIDhidden=" + id + "&View=View'>Click for more info</a></p>" +
                         "<div>";

                     google.maps.event.addListener(marker, 'click', (function(marker, content, infowindow) {
                         return function() {
                             infowindow.setContent(content);
                             infowindow.open(map, marker);
                         }
                     })(marker, content, infowindow));
                 }
             }
         </script>
    </ul>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="?pageno=1">1</a></li>
            <li class="page-item"><a class="page-link" href="?pageno=2">2</a></li>
            <li class="page-item"><a class="page-link" href="?pageno=3">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>
        <div class="empty-box">
        </div>

<?php require('template/footer.phtml') ?>