<?php
include_once('template/header.phtml'); ?>
<div class="empty-box">
</div>
    <div class="signup-form">
        <form action="/registration.php" method="post">
            <h2>Register</h2>
            <p class="hint-text">Create your account. It's free and only takes a minute.</p>
            <div class="form-group">
                <label for="sel1">Title:</label>
                <select class="form-control" id="sel1" required="required" name="title">
                    <option>Mr.</option>
                    <option>Mrs.</option>
                    <option>Ms.</option>
                    <option>Miss.</option>
                    <option>Dr.</option>
                </select>
            </div>
            <div class="form-group">
                <div class="col-xs-6"><input type="text" class="form-control" name="first_name" placeholder="First Name" required="required"></div>
            </div>
            <div class="form-group">
                <div class="col-xs-6"><input type="text" class="form-control" name="last_name" placeholder="Last Name" required="required"></div>
            </div>
            <div class="form-group">
                <input type="email" class="form-control" name="email" placeholder="Email" required="required">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password" required="required">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password" required="required">
            </div>
            <fieldset class="form-group" >
                    <legend class="checkbox-inline">Choose account type</legend>
                    <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="accountType" id="gridRadios1" value="Personal" checked>
                            <label class="form-check-label" for="gridRadios1" >
                                Personal
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="accountType" id="gridRadios2" value="Pending">
                            <label class="form-check-label" for="gridRadios2">
                                Business
                            </label>
                        </div>
                    </div>
            </fieldset>
            <div class="form-group">
                <label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a></label>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-lg btn-block">Register Now</button>
            </div>
        </form>
<?php
include_once ('template/footer.phtml'); ?>