    </div>
</main>
<footer class="camp-end"
    <div class="row">
        <div id="footer" class="col-xs-12">
            <p>
                Website is designed for University of Salford
                <br>
                &#9400; Created by Vadims Seimanovs
            </p>
        </div>
    </div>
    </footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>